// keys declare
// MOBILEATA
//CAMERADATA
//LAPTOPDATA

const MOBILE_DATA = "MOBILE_DATA";
const CAMERA_DATA = "CAMERA_DATA";
const LAPTOP_DATA = "LAPTOP_DATA";
const TABLET_DATA = "TABLET_DATA";
const MONITOR_DATA = "MONITOR_DATA";
const CART_DATA ="CART_DATA";
export {MOBILE_DATA,CAMERA_DATA,LAPTOP_DATA,TABLET_DATA,MONITOR_DATA,CART_DATA }